- name: Frontend Setup
  hosts: all
  become: yes
  tasks:
    - name: add node 22 repo
      ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_22.x | bash -

    - name: Install Nginx 1.26
      ansible.builtin.dnf:
          name:
            - '@nginx:1.26'
            - nodejs
          state: installed

    - name: Remove default nginx content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: copy nginx conf
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Download and Extract App content
      ansible.builtin.unarchive:
          src: https://raw.githubusercontent.com/raghudevopsb88/wealth-project/main/artifacts/frontend.tar.gz
          dest: /usr/share/nginx
          remote_src: yes

    - name: Install dependencies
      ansible.builtin.shell: npm ci; npm run build; mv dist html
      args:
        chdir: /usr/share/nginx/

    - name: Start Nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: started
        enabled: yes









