- name: Postgresql Setup
  hosts: all
  become: yes
  tasks:
    - name: Install Postgresql 16 repo
      ansible.builtin.dnf:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: installed
        disable_gpg_check: yes

